import { BorderBottom } from "@mui/icons-material";
import Colors from "../colors";
const styles = {
  boxMargin: {
    marginBottom: "15px",
    marginTop: "15px",
  },
  productName: {
    fontSize: { md: "40px", sm: "20px" },
    marginBottom: "5px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "normal",
  },
  moreProduct: {
    fontSize: { md: "32px", sm: "16px" },
    marginBottom: "5px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "normal",
    textAlign: { xs: "center", md: "left" },
  },
  createdBy: {
    fontSize: { md: "16px", sm: "20px" },
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "normal",
    marginBottom: "10px",
    display: "inline-flex",
    gap: "4px",
    flexWrap: "wrap",
  },
  boxDisplay: {
    display: "flex",
    alignItems: "center",
  },
  cardContentDisplay: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexDirection: "row",
  },
  buttonDisplay: {
    background: Colors.primary,
    color: Colors.white,
    padding: "0.4rem 0.6rem",
    textTransform: "capitalize",
    width: "100%",
    fontFamily: "Be Vietnam Pro , sans-serif",
  },
  iconShareDisplay: {
    display: "flex",
    width: "20%",
    justifyContent: "space-around",
    alignItems: "center",
  },

  productPrice: {
    fontSize: { md: "20px", sm: "20px" },
  },
  priceTitle: {
    fontSize: { md: "24px", sm: "20px" },
    color: Colors.primary,
  },
  priceText: {
    fontSize: { md: "24px", sm: "20px" },
    color: Colors.black,
  },
  detailsText: {
    fontSize: { md: "12px" },
    color: Colors.black,
  },
  addCard: {
    width: "100%",
    background: Colors.secondary,
    textTransform: "capitalize",
    padding: "0.4rem 0.6rem",
    fontFamily: "Be Vietnam Pro , sans-serif",
  },
  productsInfoHeading: {
    leadingTrim: "both",
    textEdge: "cap",
    fontSize: "16px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "normal",
  },
  moreProducts: {
    width: "768px",
    height: "28px",
    flexShrink: "0",
    fontFamily: "Be Vietnam",
    fontSize: "32px",
    fontStyle: "normal",
    fontWeight: "700",
    lineHeight: "normal",
    paddingTop: "20px",
  },

  sliderBoxDiv: {
    display: "flex",
    justifyContent: "center",
    width: "100%",
  },

  sliderOuterCard: {
    width: "1104px",
    height: "374px",
    flexShrink: "0",
    borderRadius: "15px",
    background: "#FFF",
    boxShadow: " 0px 0px 20px 1px rgba(0, 0, 0, 0.15)",
    zIndex: "1",
    margintop: "",
  },

  innerCardDisplay: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginTop: "40px",
    marginBottom: "40px",
  },
  innerCardDisplaySwiper: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",

    opacity: "1",
  },
  InnerCardStyle: {
    borderRadius: "10px",
    background: "#F8F9FA",
    minWidth: "200px",
    minHeight: "20vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  InnerCardStyleActive: {
    borderRadius: "10px",
    background: Colors.primary,
    minWidth: "200px",
    minHeight: "20vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  cardText: {
    fontFamily: "Be Vietnam Pro,sans-serif",
    fontSize: "16px",
    marginTop: "10px",
  },
  cardTextActive: {
    fontFamily: "Be Vietnam Pro,sans-serif",
    fontSize: "16px",
    color: Colors.white,
    marginTop: "10px",
  },

  cardContent: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  silderHeading: {
    textAlign: "center",
    marginTop: "50px",
    fontFamily: "Be Vietnam Pro,sans-serif",
    color: "black",
    fontWeight: "500",
    "@media (max-width: 500px)": {
      // Adjust styles for screens with a minimum width of 960px
      fontSize: "25px",
      padding: "0px 2px",
    },
  },
  mainBox: {
    // marginTop: { md: "5rem", xs: "4rem" },
    // padding: { md: "3px 3rem", xs: "auto" },
  },
  CardTypo: {
    fontWeight: 600,
    fontSize: { md: "32px", xs: "20px" },
    color: "#000000",
    fontFamily: "Be Vietnam Pro , sans-serif",
    marginTop: "20px",

    textAlign: "center",
  },
  CardTypo2: {
    fontWeight: 400,
    fontSize: { md: "16px", xs: "14px" },
    color: "#000000",
    fontFamily: "Be Vietnam Pro , sans-serif",
    lineHeight: "23.38px",
    textAlign: "center",
  },

  BoxStyle: {
    // boxShadow: " 0px 0px 15px 0px #0000001A",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
    padding: "0.7rem",
    borderRadius: "15px",
  },
  ImgStyle: {
    width: "100%",
    height: "200px",
    borderRadius: "2px, 2px, 0px, 0px",
    objectFit: "cover",
  },
  BoxTypo: {
    fontWeight: 500,
    fontSize: { md: "24px", xs: "18px" },
    color: "#000000",
    fontFamily: "Be Vietnam Pro , sans-serif",
    lineHeight: "20.45px",
    textAlign: "left",
    "@media (min-width: 900px)": {
      fontSize: "20px",
    },
  },
  BoxTypo2: {
    fontWeight: 500,
    fontSize: { md: "14px", xs: "12px" },
    color: "#000000",
    fontFamily: "Be Vietnam Pro , sans-serif",
    lineHeight: "20.45px",
    textAlign: "left",
  },
  PriceTypo: {
    fontWeight: 400,
    fontSize: { md: "18px", xs: "14px" },
    color: "#787878",
    fontFamily: "Be Vietnam Pro , sans-serif",
    lineHeight: "26.3px",
    textAlign: "left",
  },
  PriceTypo2: {
    fontWeight: 500,
    fontSize: { md: "18px", xs: "14px" },
    color: Colors.primary,
    fontFamily: "Be Vietnam Pro , sans-serif",
    lineHeight: "26.3px",
    textAlign: "left",
  },
  SalesTypo: {
    fontWeight: 400,
    fontSize: { md: "12px", xs: "12px" },
    color: "#787878",
    fontFamily: "Be Vietnam Pro , sans-serif",
    lineHeight: "26.3px",
    textAlign: "left",
  },
  BtnStyle: {
    background: Colors.primary,
    color: "#FFFFFF",
    padding: "0.4rem 0.6rem",
    textTransform: "capitalize",
    ":hover": {
      background: Colors.primary,
    },
  },
  imgBoxDiv: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  onHoverImageTextStyle: {
    textDecoration: "none",
    color: Colors.white,
    fontSize: "40px",
    fontFamily: "Be Vietnam Pro",
    fontWeight: 500,
    textShadow: "0px 4px 4px rgba(0, 0, 0, 0.25)",
  },
  arrowLeft: {
    background: "white",
    color: "#2796FB",
    borderRadius: "50%",
    border: 0,
    zIndex: 1,
    position: "absolute",
    left: "-1rem",
    cursor: "pointer",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
  },
  arrowRight: {
    background: "white",
    color: "#2796FB",
    borderRadius: "50%",
    border: 0,
    zIndex: 1,
    position: "absolute",
    right: "-1rem",
    cursor: "pointer",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
  },
  productBumps: {
    p: 0,
    mt: 0,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  licenseName: {
    /* Heading 24 */
    fontFamily: "Be Vietnam Pro",
    fontSize: "24px",
    fontStyle: "normal",
    fontWeight: 500,
    lineHeight: "normal",
    color: Colors.primary,
    BorderBottom: "none",
  },
};
export default styles;
